version: 2.1

save_repo: &save_repo
  save_cache:
    name: Saving Cache Repo
    key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
    paths:
      - ~/project

restore_repo: &restore_repo
  restore_cache:
    name: Restoring Cache Repo
    key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

save_packages: &save_packages
  save_cache:
    name: Saving Cache Packages
    key: v1-packages-{{ checksum "package-lock.json" }}
    paths:
      - "node_modules"
restore_packages: &restore_packages
  restore_cache:
    name: Restoring Cache Packages
    key: v1-packages-{{ checksum "package-lock.json" }}
orbs:
  docker: circleci/docker@0.5.19

jobs:
  "checkout and package dependencies":
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - *save_repo
      - *restore_packages
      - run:
          name: Installing Packages
          command: |
            npm i
      - *save_packages
#  "unit tests":
#    docker:
#      - image: circleci/node:12
#      - image: circleci/postgres:11.2-postgis-ram
#        environment:
#          POSTGRES_USER: price_manager
#          POSTGRES_PASSWORD: secret
#          POSTGRES_DB: test
#      - image: redis:5
#        name: redis
#    environment:
#      PG_HOST: postgres
#      PG_DB: test
#      PG_USER: price_manager
#      PG_PASS: secret
#      REDIS_URL: redis:///
#    steps:
#      - *restore_repo
#      - *restore_packages
#      - run:
#          name: test
#          command: |
#            npm run test

workflows:
  version: 2
  "test":
    jobs:
      - "checkout and package dependencies"
      - docker/publish:
          image: sales-agent-application
          tag: $CIRCLE_BRANCH-$CIRCLE_SHA1
          registry: prezero.azurecr.io
          context: Docker
          filters:
            branches:
              only:
                - master
