apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
    name: {{ .Values.meta.name }}
    labels:
        helm.sh/chart: {{ .Values.meta.name }}-0.1.0
        app.kubernetes.io/name: {{ .Values.meta.name }}
        app.kubernetes.io/instance: {{ .Values.meta.name }}
        app.kubernetes.io/managed-by: Tiller
    annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
    tls:
        - hosts:
              - account.prezero.dev
          secretName: letsencrypt-prod
    rules:
        - host: account.prezero.dev
          http:
              paths:
                  - path: /
                    backend:
                        serviceName: {{ .Values.meta.name }}
                        servicePort: {{ .Values.service.httpPort }}
