apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.meta.name }}
  labels:
    helm.sh/chart: {{ .Values.meta.name }}-0.1.0
    app.kubernetes.io/name: {{ .Values.meta.name }}
    app.kubernetes.io/instance: {{ .Values.meta.name }}
    app.kubernetes.io/managed-by: Tiller
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.meta.name }}
      app.kubernetes.io/instance: {{ .Values.meta.name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.meta.name }}
        app.kubernetes.io/instance: {{ .Values.meta.name }}
    spec:
      containers:
        - name: {{ .Values.meta.name }}
          image: phumberdroz/helm-notifier:{{ .Values.image.tag }}
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 0.4
              memory: 512Mi
            requests:
              cpu: 0.4
              memory: 256Mi
          ports:
            - containerPort: {{ .Values.service.httpPort }}
          env:
            - name: database-uri
              valueFrom:
                secretKeyRef:
                  name: database-uri
                  key: database-uri
